version: "3"
services:
  lidarr:
    image: dim145/deemix-server:2024-12-11
    restart: unless-stopped
    ports:
      - "6595:6595" # Deemix web UI
    volumes:
      - ${APP_DATA_DIR}/config:/deemix/config
      - ${APP_DATA_DIR}/downloads:/downloads