version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/config_deemix:/config_deemix
      - ${APP_DATA_DIR}/downloads:/downloads
      - ${APP_DATA_DIR}/music:/music