version: '3.9'
services:
    bambanah:
        image: 'ghcr.io/bambanah/deemix:latest'
        ports:
            - '6595:6595'
        volumes:
            - '${APP_DATA_DIR}/data/Deemix:/config'
            - '${APP_DATA_DIR}/data/Deemix:/downloads'
        container_name: Deemix
