services:
  goaway:
    image: pommee/goaway:latest
    container_name: goaway
    build: .
    volumes:
      - ${APP_DATA_DIR}/goaway:/home/appuser
    environment:
      - 53=${DNS_PORT:-53}
      - 8080=${WEBSITE_PORT:-8080}
    ports:
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/udp"
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/tcp"
      - "7112:${WEBSITE_PORT:-8080}/tcp"
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
