services:
    checkcle:
        image: 'operacle/checkcle:latest'
        ulimits:
            nofile:
                hard: 4096
                soft: 8192
        volumes:
            - ${APP_DATA_DIR}/checkcle:/app/pb_data
        ports:
            - '6597:8090'
        restart: unless-stopped
        container_name: checkcle
