services:
  checkcle:
    image: operacle/checkcle:latest
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "6597:8090"  # Web Application
    volumes:
      - pb_data:/app/pb_data  # Ensure persistent data across rebuilds
    ulimits:
      nofile:
        soft: 4096
        hard: 8192

volumes:
  pb_data:  # Docker-managed volume for data persistence
